# Generated by Django 4.0.5 on 2022-06-15 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название ингридиента', max_length=50, verbose_name='Название')),
                ('unit', models.CharField(choices=[('банка', 'Jar'), ('батон', 'Loaf'), ('бутылка', 'Bottle'), ('веточка', 'Branch'), ('г', 'Gr'), ('горсть', 'Handful'), ('долька', 'Slice'), ('звездочка', 'Star'), ('зубчик', 'Zub4Ik'), ('капля', 'Drop'), ('кг', 'Kg'), ('кусок', 'Chunk'), ('л', 'Liter'), ('лист', 'Leaf'), ('мл', 'Ml'), ('пакет', 'Bag'), ('пакетик', 'Bag2'), ('пачка', 'Packet'), ('пласт', 'Layer'), ('по вкусу', 'Bytaste'), ('пучок', 'Pu4Ok'), ('ст. л.', 'Table Spoon'), ('стакан', 'Glass'), ('стебель', 'Stem'), ('стручок', 'Pod'), ('тушка', 'Carcass'), ('упаковка', 'Package'), ('ч. л.', 'Tea Spoon'), ('шт.', 'Piece'), ('щепотка', 'Pinch')], help_text='Введите единицу измерения', max_length=15, verbose_name='Единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientInRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Колличество')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('hex_code', models.CharField(max_length=9, verbose_name='hex_code')),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название рецепта', max_length=50, verbose_name='Название')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, help_text='Загрузите картинку', upload_to='recipes/', verbose_name='Картинка')),
                ('description', models.TextField(help_text='Введите описание рецепта', verbose_name='Описание')),
                ('cook_time', models.IntegerField(verbose_name='Время приготовления')),
                ('author', models.ForeignKey(help_text='Автор рецепта', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('ingridients', models.ManyToManyField(through='recipes.IngredientInRecipe', to='recipes.ingredient')),
                ('tag', models.ForeignKey(blank=True, help_text='Выберите тэг', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.tag', verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.AddField(
            model_name='ingredientinrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
