# Generated by Django 4.0.5 on 2022-07-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(check=models.Q(('name__gte', 1)), name='cooking_time'),
        ),
    ]
