# Generated by Django 4.0.5 on 2022-07-04 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_rename_ingridients_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='cooking_time',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('банка', 'банка'), ('батон', 'батон'), ('бутылка', 'бутылка'), ('веточка', 'веточка'), ('г', 'г'), ('горсть', 'горсть'), ('долька', 'долька'), ('звездочка', 'звездочка'), ('зубчик', 'зубчик'), ('капля', 'капля'), ('кг', 'кг'), ('кусок', 'кусок'), ('л', 'л'), ('лист', 'лист'), ('мл', 'мл'), ('пакет', 'пакет'), ('пакетик', 'пакетик'), ('пачка', 'пачка'), ('пласт', 'пласт'), ('по вкусу', 'по вкусу'), ('пучок', 'пучок'), ('ст. л.', 'ст. л.'), ('стакан', 'стакан'), ('стебель', 'стебель'), ('стручок', 'стручок'), ('тушка', 'тушка'), ('упаковка', 'упаковка'), ('ч. л.', 'ч. л.'), ('шт.', 'шт.'), ('щепотка', 'щепотка')], help_text='Введите единицу измерения', max_length=200, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='ingredient',
            field=models.ForeignKey(help_text='Ингридиент', on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Ингридиент'),
        ),
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='recipe',
            field=models.ForeignKey(help_text='Рецепт', on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipeincart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_recipe', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipeincart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='recipeinfavorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_recipe', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AddConstraint(
            model_name='recipeinfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_favorite'),
        ),
    ]
