# Generated by Django 4.0.5 on 2022-07-12 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_follow_options_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientinrecipe',
            name='amount',
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='cooking_time',
        ),
    ]
